-- Notifications are written by the database, never by the client. `notifications`
-- has no INSERT policy for regular users, so the app's client-side insert was
-- silently denied by RLS and no like or comment ever produced a notification.
-- Granting users INSERT would let anyone forge a notification for anyone, so the
-- write moves into a SECURITY DEFINER trigger instead: it runs as the function
-- owner (bypassing RLS) and the trigger is its only caller, so the payload cannot
-- be spoofed.
--
-- metadata carries the post id so the app can open the post from the notification.

CREATE OR REPLACE FUNCTION public.notify_post_author()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_author_id uuid;
  v_title     text;
  v_message   text;
BEGIN
  SELECT author_id INTO v_author_id FROM posts WHERE id = NEW.post_id;

  -- Authorless post (posted anonymously, or the account was deleted), or acting
  -- on your own post. post_likes.user_id and post_comments.user_id are both
  -- NOT NULL, so only the author side can be NULL here.
  IF v_author_id IS NULL OR v_author_id = NEW.user_id THEN
    RETURN NEW;
  END IF;

  -- ponytail: an unlike/relike loop makes one notification per like, same as the
  -- client code this replaces. Add a "no unread like from this actor on this post"
  -- guard here if it turns into a nuisance.

  IF TG_TABLE_NAME = 'post_likes' THEN
    v_title   := 'Lượt thích mới';
    v_message := 'Có người vừa thích bài viết của bạn.';
  ELSE
    v_title   := 'Bình luận mới';
    v_message := 'Có người vừa bình luận bài viết của bạn.';
  END IF;

  -- id is supplied explicitly: Prisma's @default(uuid()) is generated by the
  -- client, so 0_init declares the column NOT NULL with no database default.
  -- A failed insert here would roll back the user's like or comment.
  INSERT INTO notifications (id, user_id, title, message, type, metadata)
  VALUES (
    gen_random_uuid(),
    v_author_id,
    v_title,
    v_message,
    CASE WHEN TG_TABLE_NAME = 'post_likes' THEN 'like' ELSE 'comment' END,
    jsonb_build_object('post_id', NEW.post_id)
  );

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS notify_post_author_on_like ON post_likes;
CREATE TRIGGER notify_post_author_on_like
  AFTER INSERT ON post_likes
  FOR EACH ROW EXECUTE FUNCTION public.notify_post_author();

DROP TRIGGER IF EXISTS notify_post_author_on_comment ON post_comments;
CREATE TRIGGER notify_post_author_on_comment
  AFTER INSERT ON post_comments
  FOR EACH ROW EXECUTE FUNCTION public.notify_post_author();
